kind: pipeline
name: default

steps:
  - name: Build
    image: gugod/perl-testbox:5.28
    commands:
      - cpanm -q --notest --no-man-pages --installdeps .
      - yath --qvf
      - git clean -xdf
      - mbtiny dist
      - ls -l

  - &installation
    name: Install (perl 5.30)
    image: perl:5.30
    depends_on:
      - Build
    commands:
      - echo *.tar.gz
      - cpanm --notest -q *.tar.gz
      - cpanm -q *.tar.gz

  - << : *installation
    name: Install (perl 5.28)
    image: perl:5.28

  - << : *installation
    name: Install (perl 5.26)
    image: perl:5.26

  - << : *installation
    name: Install (centos, perl 5.26)
    image: centos/perl-526-centos7:latest
    commands:
      - curl -L https://cpanmin.us | perl - App::cpanminus
      - echo *.tar.gz
      - cpanm --notest -q *.tar.gz
      - cpanm -q *.tar.gz

  - << : *installation
    name: Install (perl 5.24)
    image: perl:5.24

  - << : *installation
    name: Install (perl 5.22)
    image: perl:5.22

  - << : *installation
    name: Install (perl 5.20)
    image: perl:5.20

  - << : *installation
    name: Install (perl 5.18)
    image: perl:5.18
