kind: pipeline
name: default

steps:
  - name: Test with perl 5.28.0
    image: perl:5.28.0
    commands:
      - cpanm -q --notest --no-man-pages --installdeps .
      - cpanm -q --notest --no-man-pages Test2::Harness
      - yath --qvf

  - name: Build Distribution
    image: perl:5.28.0
    commands:
      - cpanm -q --notest --no-man-pages App::ModuleBuildTiny
      - git clean -xdf
      - mbtiny dist
      - ls -l

  - name: Install (perl 5.30)
    image: perl:5.30
    commands:
      - echo *.tar.gz
      - cpanm -q *.tar.gz

  - name: Install (perl 5.28)
    image: perl:5.28
    commands:
      - echo *.tar.gz
      - cpanm -q *.tar.gz

  - name: Install (perl 5.26)
    image: perl:5.26
    commands:
      - echo *.tar.gz
      - cpanm -q *.tar.gz

  - name: Install (perl 5.18)
    image: perl:5.18
    commands:
      - echo *.tar.gz
      - cpanm -q *.tar.gz
