kind: pipeline
name: default

steps:
  - name: Test with perl 5.28.0
    image: perl:5.28.0
    commands:
      - cpanm -q --notest --no-man-pages --installdeps .
      - cpanm -q --notest --no-man-pages Test2::Harness
      - yath --qvf

  - name: Build Distribution
    image: perl:5.28.0
    commands:
      - cpanm -q --notest --no-man-pages App::ModuleBuildTiny
      - git clean -xdf
      - ls -l
      - mbtiny dist
  - name: Install Distribution
    image: perl:5.28.0
    commands:
      - ls -l
      - cpanm -q *.tar.gz
