version: 2
jobs:
  criticism:
    docker:
      - image: gugod/perlcritic:latest
    steps:
      - checkout
      - run:
          name: perlcritic
          command: perlcritic --profile .perlcriticrc .
  build:
    docker:
      - image: perl:5.28
    steps:
      - checkout
      - run:
          name: Greeting
          command: perl -V
      - run:
          name: Prepare
          command: cpanm --notest Test2::Harness; cpanm --notest --installdeps .
      - run:
          name: Test
          command: yath
