version: 2
jobs:
  build:
    docker:
      - image: perl:5.28
    steps:
      - checkout
      - run:
          name: Greeting
          command: perl -V
      - run:
          name: Prepare
          command: cpanm --notest Test2::Harness
      - run:
          name: Test
          command: yath
